finos/morphir-scala

- .github/workflows/ci.yml
- project/modules/shared.sc
Switch to using mill-ci-release
> Fix Publishing

- morphir/toolkit/core/src/org/finos/morphir/ddl/DDL.scala
Initial specification for Morphir DDL
> Initial DDL specification

- morphir/datamodel/src/org/finos/morphir/datamodel/Concept.scala
- morphir/datamodel/src/org/finos/morphir/datamodel/Data.scala
Adding additional types to the DDL and reorganizing slightly
> Additional Basic types for Domain-Model

- examples/morphir-elm-projects/evaluator-tests/morphir.json
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/SkdBasicTests.elm
This PR introduces pretty comprehensive Elm code coverage (to serve as both examples and tests of morphir-scala generation) of the org.finos.morphir.ir.sdk.Basics module.
- One can use ellie-app.com to run the tests manually
- Use morphir-elm develop to start the local HTTP server to inspect generated IR
> FINCORE-15398: SDK Basic Module Tests

- morphir/datamodel/src-3/org/finos/morphir/datamodel/DeriverMacros.scala
- morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataEnums.scala
* Derivation of product-field which was an enum was not working correctly, needed to fix that
* Also needed lightly better error messages when enum derived was not found.
* Also consolidated some code from Deriver.gen and GenericProductDeriver.gen
> Fixing deriver for enum-field of coproduct

- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/NativeReferenceTests.elm
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorDDLTests.scala
Added a test for an easy SDK function
> Added test

- morphir/toolkit/core/src/org/finos/morphir/ir/Value.scala
- morphir/toolkit/core/src/org/finos/morphir/ir/conversion/ToMorphirValue.scala
- morphir/toolkit/core/test/src/org/finos/morphir/ir/conversion/ValueConversionSpec.scala
Fixes to correctly type curried apply nodes
> Currying fix

- examples/morphir-elm-projects/evaluator-tests/morphir.json
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/DictionaryTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/SetTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/Utils.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/EvaluatorQuick.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/GatherReferences.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
- morphir/src/org/finos/morphir/datamodel/Concept.scala
- morphir/src/org/finos/morphir/datamodel/ConceptStatefulTransformer.scala
- morphir/src/org/finos/morphir/datamodel/Data.scala
- morphir/src/org/finos/morphir/datamodel/PrintSpec.scala
- morphir/src/org/finos/morphir/datamodel/QualifiedNameCollector.scala
- morphir/src/org/finos/morphir/util/PrintMDM.scala
- morphir/toolkit/core/src/org/finos/morphir/ir/conversion/ToMorphirType.scala
- morphir/toolkit/core/src/org/finos/morphir/ir/conversion/ToMorphirValue.scala
- morphir/toolkit/core/test/src/org/finos/morphir/ir/conversion/TypeConversionSpec.scala
- morphir/toolkit/core/test/src/org/finos/morphir/ir/conversion/ValueConversionSpec.scala
Also needed to add support for Sets in Data, Concept, SetResult, SetRef
> Ingestor Morphir SDK Support: Set.fromList

- morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala
Ned forgot to change the new SetResult with his type checker changes.
> Fix Type checker merge

- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ListTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/StringTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
Adds List.isEmpty SDK method and tests
> List methods

- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ListTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/StringTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
Adds String SDK methods and tests for
- left
- fromFloat
- fromInt
- toInt
- isEmpty
> String methods

- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/TupleTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
Adds Tuple SDK methods and Tests for
- first
- second
> Tuple methods

- examples/morphir-elm-projects/evaluator-tests/morphir.json
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/DecimalTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/StringTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/TupleTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
Adds Decimal SDK methods and tests for 
- fromFloat
- toFloat
- toString
> Decimal methods

- examples/morphir-elm-projects/evaluator-tests/morphir-hashes.json
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/SdkBasicTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
* Add Basics.round (and tests)
* Add tests for Basics.multiply
> Test Basics.multiply, Add Basics.round

- examples/morphir-elm-projects/evaluator-tests/morphir-hashes.json
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ListTests.elm
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
- morphir/src/org/finos/morphir/runtime/RTValue.scala
Fixes a specific evaluator bug, and adds a test that would have caught it
> Definition function fix

- morphir-cli
- morphir-cli-install.sh
- morphir-cli-local-install.sh
Cleaning up and updating comments in installation scripts
> updating installation scripts

- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
- morphir/src/org/finos/morphir/runtime/sdk/BasicsSDK.scala
Per Damian, integerDivide with divisor zero returns zero.
> Address Divide-By-Zero in integerDivide

- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/LocalDateTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/LocalTimeTests.elm
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/MaybeTests.elm
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
- morphir/src/org/finos/morphir/runtime/NativeSDK.scala
- morphir/src/org/finos/morphir/runtime/sdk/LocalTimeSDK.scala
- morphir/src/org/finos/morphir/runtime/sdk/MaybeSDK.scala
- MaybeSDK.map2
- MaybeSDK.map3
- MaybeSDK.map4
- MaybeSDK.hasValue
- LocalTimeSDK.diffInHours
- LocalTimeSDK.diffInMinutes
> Add LocalTime & Maybe SDK Functions

- .moon/tasks/tag-elm.yml
- moon.yml
- package.json
> Scala2x fixes 02

- .github/workflows/ci.yml
- examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ListTests.elm
- morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
- morphir/src/org/finos/morphir/runtime/NativeSDK.scala
- morphir/src/org/finos/morphir/runtime/RTValue.scala
- morphir/src/org/finos/morphir/runtime/internal/InvokeableEvaluator.scala
- morphir/src/org/finos/morphir/runtime/sdk/ListSDK.scala
Adds all remaining functions to the ListSDK.
> Fully implement ListSDK

- morphir/runtime/src/org/finos/morphir/runtime/TestSummary.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/testing/TestTree.scala
- morphir/runtime/src/org/finos/morphir/runtime/quick/testing/UnitTesting.scala
- morphir/runtime/test/jvm/src/org/finos/morphir/runtime/UnitTestingSpec.scala
Exposing a method for getting all the individual unit testing results.
> Exposing methods to grab individual test results
