finos/morphir-scala

build.sc, morphir/toolkit/core/src/org/finos/morphir/ir/package.scala, morphir/toolkit/core/test/src/org/finos/morphir/samples/CaseExample.scala, morphir/toolkit/interpreter/src/org/finos/morphir/interpreter/Interpreter.scala, morphir/toolkit/interpreter/test/src/org/finos/morphir/interpreter/InterpreterSpec.scala
This PR:
- Creates the interpreter module under toolkit
- Restores the archived Interpreter there to a compilable state
- Restores InterpreterSpec with only passing tests enabled
Remaining Tasks:
- Remove the three ??? instances in Interpreter. There were substantial changes to the Definition model that this PR does not address
- Restore remaining unit tests to passing (related to the above)
=> Restore Interpreter

examples/morphir-elm-projects/evaluator-tests/morphir.json, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ConstructorTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/CurrentTest.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/DestructureTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/EllieStuff.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ExampleModule.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/IfThenElseTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/LambdaTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/LetDefinitionTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/LetRecursionTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ListTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/LiteralTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/NativeReferenceTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/PatternMatchTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/RecordTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/SimpleTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/TupleTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/UserDefinedReferenceTests.elm, examples/morphir-elm-projects/evaluator-tests/tests.txt
To drive testing of the evaluator, we wanted a broad coverage of syntax features with expected results. This PR adds such to examples/morphir-elm-projects/evaluator-tests
=> Added example elm tests

build.sc, morphir/datamodel/src-3/org/finos/morphir/datamodel/Deriver.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/DeriverMacros.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/SumBuilder.scala
* summonDeriver, summonProduct deriver were not working the same way as Deriver.gen which introduces strange inconsistencies e.g. certain things are inferred as a product-type despite having no product mirror and then later fail later with a wrong error.
* Some erasure checks need to be disabled because types are being widened.
* Change datamodel.json.zio to be a CrossBuild so devMode works.
=> Update macros, fix warnings, change datamodel.json.zio to CrossBuild

mill-build/src/millbuild/crossplatform/CrossPlatform.scala, mill-build/src/millbuild/settings/ScalaSettings.scala, morphir/datamodel/json/zio/src/org/finos/morphir/datamodel/json/zio/codecs.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/Deriver.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/DeriverMacros.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/GenericProductDeriver.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/ProductBuilder.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/SumBuilder.scala, morphir/datamodel/src/org/finos/morphir/datamodel/Concept.scala, morphir/datamodel/src/org/finos/morphir/datamodel/Data.scala, morphir/datamodel/src/org/finos/morphir/datamodel/namespacing.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/NamespaceExt.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataEnums.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataRecords.scala, morphir/foundations/src/org/finos/morphir/foundations/capabilities/Show.scala
* Concept.Record now contains QualifiedName
* Concept.Enum now contains QualifiedName
* Concept.Alias now contains QualifiedName
* Minor changes to Data.Record and other constructors to accommodate the QualifiedName
* Various changes to Deriver macros to accommodate QualifiedName
* GlobalNamespace and TypeNamespace typeclasses introduced so that users can specify which namespaces projects can use on a global or per-type basis. TypeNamesapce can also override the LocalName of a type (in case we need to change it and we do not control it e.g. it's from a library).
* Ergonomic additions to Namespace could not be introduced into NamespaceOps due to bogus Scala 3 errors. They were introduced via a separate Scala-3 only file called NamespaceExt that uses the Scala-3 `extension` construct. 
* …
=> Update macros with Namespace, minor build update

CustomizeTheBuild.md, README.md, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/EnumTest.elm, morphir/datamodel/src-2/datamodel/Deriver.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/Deriver.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/Derivers.scala, morphir/datamodel/src-3/org/finos/morphir/datamodel/EnumWrapper.scala, morphir/datamodel/src/org/finos/morphir/datamodel/Data.scala, morphir/datamodel/src/org/finos/morphir/datamodel/SingleEnumWrapper.scala, morphir/datamodel/src/org/finos/morphir/datamodel/SpecificDeriver.scala, morphir/datamodel/src/org/finos/morphir/datamodel/namespacing.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/EnumWrapperSpec.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/PrintSpecExample.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataCollections.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataEnums.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataOptional.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataPrimitives.scala, morphir/datamodel/test/src-3/org/finos/morphir/datamodel/ToDataRecords.scala
* Add constructors to Data.Basic elements to construct single-value wrapper enums 
e.g. `type DollarAmount = DollarAmount Int` in the form of: 
`Data.Int.deriveEnumWrapper[ScalaDollarAmount]("DollarAmount", _.toInt)`
* Move givens inside Derivers to directly into `org.finos.morphir.datamodel` package so you can just do a star-import from the package.
* Add a doc `CustomizeTheBuild.md` that describes how to enable dev-mode and how to use the build settings to disable js/native builds.
=> [WIP] Add Data.Basic EnumWrappers. Move derivers to datamodel base.

morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala, morphir/src-3/org/finos/morphir/datamodel/Deriver.scala, morphir/src-3/org/finos/morphir/datamodel/DeriverMacros.scala, morphir/src-3/org/finos/morphir/datamodel/EnumTranslation.scala, morphir/src-3/org/finos/morphir/datamodel/EnumWrapper.scala, morphir/src-3/org/finos/morphir/datamodel/SumBuilder.scala, morphir/src/org/finos/morphir/datamodel/Concept.scala, morphir/src/org/finos/morphir/datamodel/Data.scala, morphir/src/org/finos/morphir/datamodel/PrintSpec.scala, morphir/src/org/finos/morphir/util/Compare.scala, morphir/src/org/finos/morphir/util/PrintDiff.scala, morphir/test/src-3/org/finos/morphir/datamodel/ToDataEnums.scala, morphir/test/src-3/org/finos/morphir/datamodel/ToDataEnumsSimple.scala, morphir/toolkit/codec/zio/json/test/src/org/finos/morphir/ir/json/util/CustomAssert.scala, morphir/toolkit/core/src/org/finos/morphir/ir/conversion/ToMorphirType.scala, morphir/toolkit/core/src/org/finos/morphir/ir/conversion/ToMorphirValue.scala
* Introduce configuration parameter into GlobalDatamodelContext which allows Enum derivation as single-record enum (this is the new default!)
* Fixed respective tests that use this and added tests for the new behavior
* Fixed PrintSpec
* Move PrintDiff and Compare into morphir-runtime utils package
=> Enums optionally can be Single-Record-Constructor Types

morphir/extensibility/src/org/finos/morphir/Names.scala, morphir/extensibility/src/org/finos/morphir/NamingOptionsModule.scala, morphir/extensibility/src/org/finos/morphir/fqname.scala, morphir/extensibility/src/org/finos/morphir/nodeID.scala, morphir/extensibility/src/org/finos/morphir/qualifiedModuleName.scala
* QualifiedModuleName needs a toString to print easily.
* Also should have a fromString to parse easily.
* In order to do that, need to add helpers similar to fqn. I called them `qmn`.
* Also, it's easiest to reuse FQNaming options so I extracted that out into a separate module.
=> Add Printing and fromString to QualifiedModuleName

examples/morphir-elm-projects/evaluator-tests/morphir-hashes.json, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/DictionaryTests.elm, morphir/runtime/src/org/finos/morphir/runtime/MorphirRuntimeError.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/EvaluatorQuick.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Helpers.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/NativeFunctionSignature.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Store.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/TupleSigniture.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
* Make `Result.Tuple(Any)` argument typed similar to the way SDKNativeFunction was done.
* Make `Result.NativeFunction(Any)` type similar to the way SDKNativeFunction was done
* Needed a few helpers for the above things e.g. List => Tuple translation (that stuff exists in the standard library but only in Scala 3 and we're cross-compiling the evaluator)
* Needed a few helpers to convert NativeFunctionSignature if it takes a store (i.e. something that can execute inside of a native function like `List.map`)
* These things required various changes in `EvaluatorQuick.scala` and `Loop.scala`
* Implemented `Dict.toList` and fixed up `Dict.fromList`. Added a test.
=> Make Result.Tuple(Any) typed, better Dict.fromList, add Dict.toList

morphir/runtime/src/org/finos/morphir/runtime/Succinct.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/EvaluatorQuick.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/GatherReferences.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/NativeFunctionSignature.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/QuickMorphirRuntime.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Result.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Store.scala, morphir/toolkit/core/src/org/finos/morphir/ir/internal/ValueDefinition.scala
* Passing around the `Store` object in the Native SDK objects does not conceptually make sense, pass around the evaluator instead.
* Instead of passing around global evaluator definitions in the Store object, separate them out into `GlobalDefs` and pass those around. This significantly simplifies many evaluator functions including `handleApplyResult` which Native often uses. This involved breaking things aren't actually the call-stack (i.e. global definitions) from Store. They don't make sense in there anyway.
* Add a `handleApplyResult2` which helps calling native functions that have lambdas with multiple arguments e.g. `Dict.filter` (which has `k` and `v` arguments).
=> Simplify Evaluator calls in Native Functions

examples/morphir-elm-projects/evaluator-tests/morphir-hashes.json, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ListTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/SdkBasicTests.elm, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/StringTests.elm, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
* Implement List.partition and List.any
* Implement >= and <= for numerics
=> Implement List.partition, List.any, `>=` and `<=`

morphir/runtime/src/org/finos/morphir/runtime/TypeChecker.scala, morphir/runtime/src/org/finos/morphir/runtime/Utils.scala
* Typechecker was not dealising aliases that exist in the middle of a curried function
* Typechecker was not dealising leaf types
* Both of these issues were causing issues in client code
=> Typechecker needs to do additional deliasing

morphir/runtime/src/org/finos/morphir/runtime/TypeChecker.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/TypeCheckerTests.scala.scala
Previously the type checker was only running agains the entry point, i.e., checking that arguments were well-formed and matched the definition of the entry point function. This is probably all we want in terms of live performance, but it meantthe tests for the type checker were less rigorous than might be hoped.
This PR adds additional type checker functionality to bulk test all definitions within a set of distributions, and adds such to the type checker test spec. This uncovered a few more minor type checker bugs, which are also fixed here.
=> Type checker additional tests

morphir/main/src/org/finos/morphir/cli/MorphirCliMain.scala, morphir/main/src/org/finos/morphir/cli/MorphirCommand.scala, morphir/tools/js/src/org/finos/morphir/service/MorphirBundlePlatformSpecific.scala, morphir/tools/jvm-native/src/org/finos/morphir/service/MorphirBundlePlatformSpecific.scala, morphir/tools/src/org/finos/morphir/service/MorphirBundle.scala
`libarary` command to split Bundle Morphir IR model(s) into Library Morphir IR model(s) using the Morphir Runtime
=> Library morphir-cli command

morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala, morphir/src/org/finos/morphir/datamodel/Concept.scala, morphir/src/org/finos/morphir/datamodel/Data.scala, morphir/src/org/finos/morphir/ir/printing/PrintIR.scala, morphir/src/org/finos/morphir/runtime/ErrorUtils.scala, morphir/src/org/finos/morphir/util/PrintMDM.scala, morphir/src/org/finos/morphir/util/PrintRTValue.scala
This PR adds a pretty printer for RTValues, to improve readability of error messages and failed tests.
This included a minor refactor to PrintMDM, as different DetailLevel traits are required for each.
Additionally, added extra digits of precision to the value of Pi, in response to feedback.
=> Print RTValue

morphir/runtime/src/org/finos/morphir/runtime/Extractors.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/TypeCheckerTests.scala.scala
Fix (and added additional testing) for a bug relating to type dealiasing
A prior PR addressed an issue where opaque types were being rejected on entry points due to the use of `lookupTypeSpecification` rather than `lookupTypeDefinition`. This fix was not applied to the extractor utility functions which are used by the type checker. Because these are only used in deeper type checking (which is currently only called by tests), it was not immediately caught.
This PR applies that fix to the extractor utility. Additionally, it expands the distributions the type checker covers to include some which use opaque types (so that this or similar bugs will be caught in the future).
=> fix for dealiasing extractor

morphir/src/org/finos/morphir/runtime/sdk/DecimalSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/ListSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/LocalDateSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/LocalTimeSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/MaybeSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/ResultSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/StringSDK.scala
This PR addresses https://github.com/finos/morphir-scala/issues/575 by renaming some mis-named helper functions in MaybeSDK
=> Fixed mis-named function and added comments

examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/StringTests.elm, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala, morphir/src/org/finos/morphir/runtime/NativeSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/StringSDK.scala
This PR adds support for the below String functions
- sdk.StringSDK.fromChar
- sdk.StringSDK.cons
- sdk.StringSDK.uncons
- sdk.StringSDK.toList
- sdk.StringSDK.fromList
- sdk.StringSDK.pad
- sdk.StringSDK.map
- sdk.StringSDK.filter
- sdk.StringSDK.foldl
- sdk.StringSDK.foldr
- sdk.StringSDK.any
- sdk.StringSDK.all
=> Add remaining String SDK Functions

README.md
Fixes a broken link to [contributions guidelines](https://github.com/finos/morphir-scala/blob/main//CONTRIBUTING.md).
=> Fix a broken link to contributions guidelines

examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/SdkBasicsTests.elm, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala, morphir/src/org/finos/morphir/runtime/Coercer.scala, morphir/src/org/finos/morphir/runtime/NativeSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/BasicsSDK.scala
Adds missing functionality for Float function as defined [here](https://github.com/finos/morphir/blob/main/docs/scala/support.md)
=> Add missing functionality to BasicSDK.Float

examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ConstructorTests.elm, morphir/runtime/src/org/finos/morphir/runtime/TypeChecker.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Store.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala, morphir/src/org/finos/morphir/runtime/NativeSDK.scala, morphir/src/org/finos/morphir/runtime/RTValue.scala, morphir/src/org/finos/morphir/runtime/SDKValue.scala, morphir/src/org/finos/morphir/util/PrintRTValue.scala
This closes a bug in which Implicit Record Constructors were not properly supported in the morphir-scala evaluator.
=> Implicit record support

examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/AggregateTests.elm, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala, morphir/src/org/finos/morphir/runtime/Coercer.scala, morphir/src/org/finos/morphir/runtime/NativeSDK.scala, morphir/src/org/finos/morphir/runtime/RTValue.scala, morphir/src/org/finos/morphir/runtime/sdk/AggregateSDK.scala, morphir/src/org/finos/morphir/runtime/sdk/KeySDK.scala, morphir/src/org/finos/morphir/util/PrintRTValue.scala
Adds the aggregateMap(2/3/4) functions and all relevant Aggregations. Key objects 0-16 added, but respective SDK has not been added.
Commit history is a bit messy for this PR, can squash if it would improve clarity.
=> Add Aggregate.aggregateMap functions

examples/morphir-elm-projects/evaluator-tests/morphir.json, examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ExceptionTests.elm, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
Adds logic to the EvaluatorMDMTests that allows for testing situation where we expect exceptions to get thrown. Also adds some simplified testing to test specific exceptions getting thrown.
An added benefit of this setup is that tests for unhappy path testing should be easier to write going forward (when they expect exceptions to get thrown)
=> Add tests for some MorphirRuntimeErrors

README.md
Adds a section that redirects from the root readme to the elm testing readme. This should make it easier for anyone working on the elm tests to find the relevant documentation.
Also adds an alternative means to format the elm code using elm-format from the root directory (rather than having to navigate to examples/morphir-elm-projects/evaluator-tests/ to do so)
=> Clean up readme 

README.md
* Clean up readme to reference handling elm tests as well as an alternative way to run elm-format from the project root directory
* move
=> Merging main to 0.4.x

examples/morphir-elm-projects/evaluator-tests/src/Morphir/Examples/App/ExceptionTests.elm, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala
Adds coverage for the following errors:
- SizeMismatch
- ValueLacksField
- ValueHasExtraField
- ManyTypeErrors
- LiteralTypeMismatch
- TypesMismatch
- ResultTypeMismatch
- UnmatchedPattern
- InferenceConflict
=> Increase error testing for MorphirRuntimeErrors

README.md, build.sc, project/deps.sc
Add test coverage to available mill ops. 
Test coverage is handled with the scoverage plugin.
This does not in any way interact with existing github actions and the coverage tests are only run manually for the time being. Coverage requirements can be added later (likely with a ratcheting coverage goal that caps out at a certain level)
=> Add test coverage to mill

morphir/runtime/src/org/finos/morphir/runtime/MorphirRuntime.scala, morphir/runtime/src/org/finos/morphir/runtime/TypeChecker.scala, morphir/runtime/src/org/finos/morphir/runtime/TypedMorphirRuntime.scala, morphir/runtime/src/org/finos/morphir/runtime/Utils.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Loop.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/Native.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/QuickMorphirRuntime.scala, morphir/runtime/src/org/finos/morphir/runtime/quick/testing/UnitTesting.scala, morphir/runtime/test/jvm/src/org/finos/morphir/runtime/EvaluatorMDMTests.scala, morphir/src/org/finos/morphir/runtime/MorphirRuntimeError.scala
This code breaks out the CodeLocation into the individual errors themselves. This unfortunately does not yet allow for the elimination of the TopLevelError, but it gets everything closer to eliminating it. In most scenarios, CodeLocation should be available, but there are spots where no obvious location maps to the error. As such, making the CodeLocation option seems sensable. Also, given a stack of CodeLocations, only the top of the stack will be considered the "location" for the purpose of AttachedLocation.
=> Add CodeLocation to most Morphir errors
